name              'docker'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides docker_service, docker_image, and docker_container resources'
version           '7.2.2'
source_url        'https://github.com/sous-chefs/docker'
issues_url        'https://github.com/sous-chefs/docker/issues'
chef_version      '>= 15.0'

supports 'amazon'
supports 'centos'
supports 'scientific'
supports 'oracle'
supports 'debian'
supports 'fedora'
supports 'redhat'
supports 'ubuntu'

gem 'docker-api', git: 'https://github.com/coupa-ops/docker-api.git', ref: '66f4043d57317c2003dc4e6459fd870b097104a4'
